### ISSUE TITLE
Support for styled-components keyframes

### ISSUE THREAD

**Issue by nvanselow** [QuickBase/babel-plugin-styled-components-css-namespace#1]
Originally reported by @genedwards,  moved from other repo.

Issue: the styled-components module exports a `keyframe` function. https://www.styled-components.com/docs/basics#animations

Example usage:
```Javascript
const rotate360 = keyframes`
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(360deg);
  }
`;

const Rotate = styled.div`
  animation: ${rotate360} 2s linear infinite;
`;
```

The generated CSS from the above example looks like the following:
```CSS
@-webkit-keyframeskrrMtA{
  .<cssNamespace> from{
    -webkit-transform:rotate(0deg);
    -ms-transform:rotate(0deg);
    transform:rotate(0deg);
  }
  .<cssNamespace> to{
    -webkit-transform:rotate(360deg);
    -ms-transform:rotate(360deg);
    transform:rotate(360deg);
  }
}
@keyframes krrMtA{
  .<cssNamespace> from{
    -webkit-transform:rotate(0deg);
    -ms-transform:rotate(0deg);
    transform:rotate(0deg);
  }
  .<cssNamespace> to{
    -webkit-transform:rotate(360deg);
    -ms-transform:rotate(360deg);
    transform:rotate(360deg);
  }
}
```
