### ISSUE TITLE
Namespace break adjacent sibling combinator selector

### ISSUE THREAD

**Issue by slestang** [QuickBase/babel-plugin-styled-components-css-namespace#12]
First all thank for this plugin, is solved a very annoying CSS override issue between our 2 projects.

My issue is that:
```es6
const InfoContainer = styled.div`
  display: flex;
  & + & {
    margin-left: 0.5rem;
  }
`;
```

now generate the style ('spa' is our namespace):
```css
.sc-eHgmQL {}.spa .hVujAK{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;} .spa .hVujAK + .spa .hVujAK{margin-left:0.5rem;}
```

With that style the margin-left is never applied because the selector should be `.spa .hVujAK + .hVujAK` instead of `.spa .hVujAK + .spa .hVujAK`

Is that fixable in babel-plugin-styled-components-css-namespace?
