### ISSUE TITLE
Media Query String Interpolation Bug

### ISSUE THREAD

**Issue by zachhardesty7** [QuickBase/babel-plugin-styled-components-css-namespace#35]
Just discover what appears to be a bug with this library that causes media queries to be improperly parsed by placing the class name in the improper location. Unfortunately no error is produced so.

To reproduce
```js
const mediaQuery = '@media only screen and (min-width: 426px) and (max-width: 767px)'

const Component = styled.div`
  background-color: red;
  ${mediaQuery} {
    background-color: blue;
  }
`
```

Without interpolating the string, it works fine, but the above produces a rule like this:
```css
/* sc-component-id: sc-14zearg-1 */
.jmWrIX.jmWrIX{background-color: red;}
.jmWrIX.jmWrIX @media only screen and (min-width: 426px) and (max-width: 767px){background-color: blue;}
```

while it should produce a rule like this:
```css
/* sc-component-id: sc-14zearg-1 */
.jmWrIX.jmWrIX{background-color: red;}
@media only screen and (min-width: 426px) and (max-width: 767px){.jmWrIX.jmWrIX{background-color: blue;}}
```
